name: Build and Release

permissions:
  contents: write
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build executable
        run: pyinstaller --noconfirm --onefile src/gui.py

      - name: Rename binary
        shell: bash
        run: |
          EXT=""
          if [ "$RUNNER_OS" = "Windows" ]; then
            EXT=".exe"
          fi
          mv dist/gui${EXT} Comparador-${RUNNER_OS}${EXT}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Comparador-${{ runner.os }}
          path: Comparador-${{ runner.os }}*

  release:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
        # precisamos do histórico completo para as tags
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Determine next version
        id: version
        run: |
          git fetch --tags
          last=$(git tag -l 'v*' | sort -V | tail -n1)
          if [ -z "$last" ]; then
            ver="0.1"
          else
            num=${last#v0.}
            num=$((num + 1))
            ver="0.$num"
          fi
          echo "version=$ver" >> "$GITHUB_OUTPUT"

      - name: Extrair commits desde a última tag
        id: commits
        run: |
          prev_tag=$(git tag -l 'v*' | sort -V | tail -n2 | head -n1)
          git log "$prev_tag"..HEAD --pretty=format:"- %s" > changelog.md
          # transforma quebras de linha em \n
          logs=$(awk '{printf "%s\\n", $0}' changelog.md)
          echo "logs=$logs" >> "$GITHUB_OUTPUT"

      - name: Gerar release notes com curl
        id: ai_notes_curl
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          prev=$(git tag -l 'v*' | sort -V | tail -n2 | head -n1)
          logs=$(git log $prev..HEAD --pretty=format:"- %s")
          summary=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
                --arg logs "$logs" \
                '{
                  model: "gpt-4o-mini",
                  messages: [
                    {role: "system", content: "Você é um gerador de changelog. Resuma as mudanças de forma clara e concisa."},
                    {role: "user", content: $logs}
                  ]
                }')"
          )
          # extrai só a parte do texto
          notes=$(echo "$summary" | jq -r '.choices[0].message.content')
          echo "release_notes<<EOF\n$notes\nEOF" >> $GITHUB_OUTPUT

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          artifacts: artifacts/**
          body: |
            Release automatically generated for version v${{ steps.version.outputs.version }}.
